# Generated by Django 5.2.17 on 2026-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(choices=[('Safari Enquiry', 'Safari Enquiry'), ('Quote Request', 'Quote Request'), ('Booking Question', 'Booking Question'), ('DMC / Corporate', 'DMC / Corporate'), ('Press / Media', 'Press / Media'), ('General Question', 'General Question')], max_length=60)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('preferred_dates', models.CharField(blank=True, max_length=120)),
                ('guests', models.CharField(blank=True, help_text="e.g. '2', '7–10'", max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('destinations', models.JSONField(blank=True, default=list)),
                ('duration', models.JSONField(blank=True, default=list)),
                ('budget', models.JSONField(blank=True, default=list)),
                ('safari_type', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Trip enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
