# Generated by Django 5.2.17 on 2026-09-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_sections_alter_page_body_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='page',
            name='hero_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='kicker',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='link_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='link_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='section_key',
            field=models.SlugField(blank=True, help_text='Stable key used by React, e.g. story, team, services.', max_length=100),
        ),
        migrations.CreateModel(
            name='PageSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True)),
                ('label', models.CharField(blank=True, max_length=160)),
                ('value', models.CharField(blank=True, max_length=160)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('link_label', models.CharField(blank=True, max_length=160)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.pagesection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
