# Generated by Django 5.2.17 on 2026-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'kenya-safari-cost'", max_length=220, unique=True)),
                ('tag', models.CharField(help_text="e.g. 'Budget Guide', 'Getting There', 'Destination'", max_length=60)),
                ('excerpt', models.CharField(help_text='Short teaser shown on the guides hub card', max_length=300)),
                ('body', models.TextField(help_text='Full article content. Plain text or HTML, rendered as-is by the frontend.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, help_text="Shown to readers as 'N min read' - set manually or estimate from word count")),
                ('author', models.CharField(blank=True, max_length=120)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first on the guides hub')),
            ],
            options={
                'ordering': ['order', '-published_at'],
            },
        ),
    ]
