# Generated by Django 5.2.17 on 2026-09-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(help_text="Used in the URL, e.g. 'tanzania'", max_length=140, unique=True)),
                ('tag', models.CharField(blank=True, help_text="e.g. 'East Africa'", max_length=80)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('highlights', models.JSONField(blank=True, default=list, help_text='List of short tags, e.g. ["Serengeti", "Ngorongoro"]')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SafariPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(help_text="e.g. 'masai-mara-3day'", max_length=180, unique=True)),
                ('subtitle', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('price_label', models.CharField(blank=True, max_length=100)),
                ('group_size', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('itinerary', models.JSONField(blank=True, default=list)),
                ('includes', models.JSONField(blank=True, default=list)),
                ('excludes', models.JSONField(blank=True, default=list)),
                ('related_links', models.JSONField(blank=True, default=list)),
                ('badge', models.CharField(blank=True, help_text="e.g. 'Best Seller', 'Seasonal', 'Premium'", max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='catalog.destination')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
