# Generated by Django 5.2.17 on 2026-09-13 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_safariexclude_safarihighlight_safariinclude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description shown in search results. Aim for roughly 140-160 characters.', max_length=170),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='seo_title',
            field=models.CharField(blank=True, help_text='SEO title shown in search results. Aim for roughly 50-60 characters.', max_length=70),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='overview',
            field=models.TextField(blank=True, help_text='Main visible SEO-focused description for this safari.'),
        ),
        migrations.CreateModel(
            name='SafariFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('safari_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='catalog.safaripackage')),
            ],
            options={
                'verbose_name': 'Safari FAQ',
                'verbose_name_plural': 'Safari FAQs',
                'ordering': ['order', 'id'],
            },
        ),
    ]
